import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const VCODER_EXPERIMENTAL = truthy("VCODER_EXPERIMENTAL")
const VCODER_DISABLE_CLAUDE_CODE = truthy("VCODER_DISABLE_CLAUDE_CODE")
const VCODER_DISABLE_CLAUDE_CODE_SKILLS =
  VCODER_DISABLE_CLAUDE_CODE || truthy("VCODER_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["VCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  VCODER_AUTO_SHARE: truthy("VCODER_AUTO_SHARE"),
  VCODER_AUTO_HEAP_SNAPSHOT: truthy("VCODER_AUTO_HEAP_SNAPSHOT"),
  VCODER_GIT_BASH_PATH: process.env["VCODER_GIT_BASH_PATH"],
  VCODER_CONFIG: process.env["VCODER_CONFIG"],
  VCODER_CONFIG_CONTENT: process.env["VCODER_CONFIG_CONTENT"],
  VCODER_DISABLE_AUTOUPDATE: truthy("VCODER_DISABLE_AUTOUPDATE"),
  VCODER_ALWAYS_NOTIFY_UPDATE: truthy("VCODER_ALWAYS_NOTIFY_UPDATE"),
  VCODER_DISABLE_PRUNE: truthy("VCODER_DISABLE_PRUNE"),
  VCODER_DISABLE_TERMINAL_TITLE: truthy("VCODER_DISABLE_TERMINAL_TITLE"),
  VCODER_SHOW_TTFD: truthy("VCODER_SHOW_TTFD"),
  VCODER_PERMISSION: process.env["VCODER_PERMISSION"],
  VCODER_DISABLE_DEFAULT_PLUGINS: truthy("VCODER_DISABLE_DEFAULT_PLUGINS"),
  VCODER_DISABLE_LSP_DOWNLOAD: truthy("VCODER_DISABLE_LSP_DOWNLOAD"),
  VCODER_ENABLE_EXPERIMENTAL_MODELS: truthy("VCODER_ENABLE_EXPERIMENTAL_MODELS"),
  VCODER_DISABLE_AUTOCOMPACT: truthy("VCODER_DISABLE_AUTOCOMPACT"),
  VCODER_DISABLE_MODELS_FETCH: truthy("VCODER_DISABLE_MODELS_FETCH"),
  VCODER_DISABLE_MOUSE: truthy("VCODER_DISABLE_MOUSE"),
  VCODER_DISABLE_CLAUDE_CODE,
  VCODER_DISABLE_CLAUDE_CODE_PROMPT: VCODER_DISABLE_CLAUDE_CODE || truthy("VCODER_DISABLE_CLAUDE_CODE_PROMPT"),
  VCODER_DISABLE_CLAUDE_CODE_SKILLS,
  VCODER_DISABLE_EXTERNAL_SKILLS: VCODER_DISABLE_CLAUDE_CODE_SKILLS || truthy("VCODER_DISABLE_EXTERNAL_SKILLS"),
  VCODER_FAKE_VCS: process.env["VCODER_FAKE_VCS"],
  VCODER_SERVER_PASSWORD: process.env["VCODER_SERVER_PASSWORD"],
  VCODER_SERVER_USERNAME: process.env["VCODER_SERVER_USERNAME"],
  VCODER_ENABLE_QUESTION_TOOL: truthy("VCODER_ENABLE_QUESTION_TOOL"),

  // Experimental
  VCODER_EXPERIMENTAL,
  VCODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("VCODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  VCODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("VCODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  VCODER_EXPERIMENTAL_ICON_DISCOVERY: VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_ICON_DISCOVERY"),
  VCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("VCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  VCODER_ENABLE_EXA: truthy("VCODER_ENABLE_EXA") || VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_EXA"),
  VCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("VCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  VCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("VCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  VCODER_EXPERIMENTAL_OXFMT: VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_OXFMT"),
  VCODER_EXPERIMENTAL_LSP_TY: truthy("VCODER_EXPERIMENTAL_LSP_TY"),
  VCODER_EXPERIMENTAL_LSP_TOOL: VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_LSP_TOOL"),
  VCODER_EXPERIMENTAL_PLAN_MODE: VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_PLAN_MODE"),
  VCODER_EXPERIMENTAL_MARKDOWN: !falsy("VCODER_EXPERIMENTAL_MARKDOWN"),
  VCODER_MODELS_URL: process.env["VCODER_MODELS_URL"],
  VCODER_MODELS_PATH: process.env["VCODER_MODELS_PATH"],
  VCODER_DISABLE_EMBEDDED_WEB_UI: truthy("VCODER_DISABLE_EMBEDDED_WEB_UI"),
  VCODER_DB: process.env["VCODER_DB"],
  VCODER_DISABLE_CHANNEL_DB: truthy("VCODER_DISABLE_CHANNEL_DB"),
  VCODER_SKIP_MIGRATIONS: truthy("VCODER_SKIP_MIGRATIONS"),
  VCODER_STRICT_CONFIG_DEPS: truthy("VCODER_STRICT_CONFIG_DEPS"),

  VCODER_WORKSPACE_ID: process.env["VCODER_WORKSPACE_ID"],
  VCODER_EXPERIMENTAL_HTTPAPI: truthy("VCODER_EXPERIMENTAL_HTTPAPI"),
  VCODER_EXPERIMENTAL_WORKSPACES: VCODER_EXPERIMENTAL || truthy("VCODER_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get VCODER_DISABLE_PROJECT_CONFIG() {
    return truthy("VCODER_DISABLE_PROJECT_CONFIG")
  },
  get VCODER_TUI_CONFIG() {
    return process.env["VCODER_TUI_CONFIG"]
  },
  get VCODER_CONFIG_DIR() {
    return process.env["VCODER_CONFIG_DIR"]
  },
  get VCODER_PURE() {
    return truthy("VCODER_PURE")
  },
  get VCODER_PLUGIN_META_FILE() {
    return process.env["VCODER_PLUGIN_META_FILE"]
  },
  get VCODER_CLIENT() {
    return process.env["VCODER_CLIENT"] ?? "cli"
  },
}
