/**
 * Agentic "Do" orchestrator: READ → PLAN → (user approves) → EXECUTE → TEST → FIX → REPORT.
 *
 * Plan is a strict JSON object generated by the LLM. We parse + validate it, render
 * to markdown for the user, then execute tasks one-by-one. Writes and bash (test runner)
 * are auto-approved once the plan is approved. Fix loop cap is 3 retries per task.
 */
import { ChatMessage, LlmConfig, chat } from './ollama';
import { runAgent } from './loop';
import { ToolContext } from './tools/types';
import { ALL_TOOLS } from './tools/registry';

export interface PlanTask {
  id: string;
  title: string;
  description: string;
  files: string[];
  acceptance: string;
}

export interface Plan {
  summary: string;
  test_command: string;
  tasks: PlanTask[];
}

export interface TaskOutcome {
  id: string;
  title: string;
  status: 'executed' | 'errored' | 'skipped';
  notes: string;
}

export interface RunVerdict {
  testPassed: boolean;
  fixAttempts: number;
  finalTestOutput: string;
}

export interface OrchestratorCallbacks {
  onPhase: (phase: string, info?: string) => void;
  onPlan: (plan: Plan) => Promise<boolean>; // return true to approve
  onReport: (markdown: string) => void;
  shouldStop: () => boolean;
}

export interface OrchestratorOptions {
  cfg: LlmConfig;
  goal: string;
  ctx: ToolContext;
  maxFixAttempts: number; // e.g. 3
  phaseAgents?: Record<string, string>; // phase name → ECC agent body (already trimmed)
  contextFiles?: string; // concatenated CLAUDE.md / AGENTS.md content
  onLlmCall?: (phase: string, msgs: ChatMessage[], schemas: unknown[]) => void; // Phase-0 instrumentation
  // Stream hooks — when provided, each phase's LLM call streams chunks to onStreamChunk.
  onStreamStart?: (phase: string) => void;
  onStreamChunk?: (phase: string, delta: string) => void;
  onStreamEnd?: (phase: string, finalText: string) => void;
  shouldStop?: () => boolean;
}

function buildSystemPrompt(phaseBase: string, agentBody?: string, contextFiles?: string): string {
  const parts = [phaseBase];
  if (agentBody && agentBody.trim()) {
    parts.push('---\n# Agent guidance (from ECC)\n\n' + agentBody);
  }
  if (contextFiles && contextFiles.trim()) {
    parts.push('---\n# Workspace context\n\n' + contextFiles);
  }
  return parts.join('\n\n');
}

const FIX_CAP_DEFAULT = 3;

interface PhaseStream {
  onStart?: () => void;
  onChunk?: (delta: string) => void;
  onEnd?: (finalText: string) => void;
  shouldAbort?: () => boolean;
}

function mkPhaseStream(opts: OrchestratorOptions, phase: string): PhaseStream | undefined {
  if (!opts.onStreamChunk) return undefined;
  return {
    onStart: () => opts.onStreamStart?.(phase),
    onChunk: (d) => opts.onStreamChunk?.(phase, d),
    onEnd: (t) => opts.onStreamEnd?.(phase, t),
    shouldAbort: () => opts.shouldStop?.() ?? false
  };
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 1 — READ: enrich the user goal (one-shot LLM call, no tools)
// ───────────────────────────────────────────────────────────────────────────────
async function phaseRead(cfg: LlmConfig, goal: string, contextFiles?: string, onLlmCall?: OrchestratorOptions['onLlmCall'], stream?: PhaseStream): Promise<string> {
  const base = [
    'You are an engineering analyst. Given a user goal, produce a concise enriched spec (max 300 words) listing:',
    '(a) **primary language/framework** — explicit. Detect from the goal, any attached files, and any workspace context below. State it in plain words (e.g. "Python + Flask", "TypeScript + React/Vite", "Go").',
    '(b) what files are likely involved (paths if known)',
    '(c) constraints/edge cases (including EVERY nuance mentioned in the goal — streaming? auth? a specific library?)',
    '(d) how success is verified (what test command or smoke test makes sense for THIS language)',
    '',
    'No code. No JSON yet — just prose. Do NOT translate the goal; if user wrote Vietnamese, keep concepts faithful to what they asked.'
  ].join('\n');
  const msgs: ChatMessage[] = [
    { role: 'system', content: buildSystemPrompt(base, undefined, contextFiles) },
    { role: 'user', content: `Goal:\n${goal}` }
  ];
  onLlmCall?.('READ', msgs, []);
  stream?.onStart?.();
  const res = await chat(cfg, msgs, [], stream?.onChunk ? { onChunk: stream.onChunk, shouldAbort: stream.shouldAbort } : undefined);
  stream?.onEnd?.(res.content || '');
  return res.content || goal;
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 2 — PLAN: produce strict JSON Plan
// ───────────────────────────────────────────────────────────────────────────────
async function phasePlan(cfg: LlmConfig, enrichedSpec: string, agentBody?: string, contextFiles?: string, onLlmCall?: OrchestratorOptions['onLlmCall'], stream?: PhaseStream): Promise<Plan> {
  const schemaExample: Plan = {
    summary: '1-line summary',
    test_command: 'npm test',
    tasks: [
      { id: 't1', title: '...', description: '...', files: ['path/to/file.ts'], acceptance: 'tests pass / function X returns Y' }
    ]
  };
  const base = [
    'You are a planner. Emit ONLY a JSON object. No markdown, no prose, no fences.',
    '',
    'Prefer FEWER, LARGER tasks. Combine tasks that touch the same file. Ideal plan: 1-3 tasks total, 4 max.',
    'Do NOT create "write tests" tasks — test_command already exists to verify.',
    'Each task should be a complete deliverable (one file end-to-end is usually one task).',
    'Respect EVERY explicit requirement from the spec (streaming, specific libraries, API endpoints). A task that produces a server without the requested streaming is a failed task.',
    '',
    'Exact schema:',
    JSON.stringify(schemaExample, null, 2),
    '',
    'Rules:',
    '- test_command: the single shell command that verifies the goal. MUST match the project language detected in the spec:',
    '    * Python → `pytest`, `python -m unittest discover`, or `python -m py_compile <main>.py` for smoke',
    '    * Node/JS → `npm test`, `npx jest`',
    '    * TypeScript → `npx tsc --noEmit` + test runner',
    '    * Go → `go test ./...`',
    '    * Rust → `cargo test`',
    '    * Java → `mvn test` / `gradle test`',
    '  For brand-new projects with no test infrastructure, use a smoke command that at least verifies syntax/imports (e.g. `python -c "import app; print(\'ok\')"` or `node --check app.js`).',
    '  NEVER default to `npm test` for non-Node projects.',
    '- Each task id is unique (t1, t2, ...).',
    '- files: workspace-relative paths you intend to touch.',
    '- acceptance: brief note on what this task delivers — include the explicit requirement (e.g. "streams tokens via NDJSON").',
    '',
    'Output the JSON object and nothing else — the schema above overrides any conflicting instruction from agent guidance.'
  ].join('\n');
  const msgs: ChatMessage[] = [
    { role: 'system', content: buildSystemPrompt(base, agentBody, contextFiles) },
    { role: 'user', content: `Enriched spec:\n${enrichedSpec}` }
  ];
  onLlmCall?.('PLAN', msgs, []);
  stream?.onStart?.();
  const res = await chat(cfg, msgs, [], stream?.onChunk ? { onChunk: stream.onChunk, shouldAbort: stream.shouldAbort } : undefined);
  stream?.onEnd?.(res.content || '');
  return parsePlan(res.content);
}

function parsePlan(raw: string): Plan {
  // Strip common fence wrappers the model may add despite instructions
  let txt = raw.trim();
  const fence = /^```(?:json)?\s*\n?([\s\S]*?)\n?```$/m.exec(txt);
  if (fence) txt = fence[1].trim();
  // Find the first { ... } block
  const start = txt.indexOf('{');
  const end = txt.lastIndexOf('}');
  if (start < 0 || end < 0 || end <= start) {
    throw new Error(`Plan phase: no JSON object in response. Raw: ${raw.slice(0, 300)}`);
  }
  const jsonStr = txt.slice(start, end + 1);
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonStr);
  } catch (e) {
    throw new Error(`Plan phase: invalid JSON (${e instanceof Error ? e.message : String(e)})`);
  }
  const p = parsed as Partial<Plan>;
  if (!p.summary || !p.test_command || !Array.isArray(p.tasks) || p.tasks.length === 0) {
    throw new Error(`Plan phase: missing required fields. Got: ${JSON.stringify(parsed).slice(0, 200)}`);
  }
  // Normalize tasks
  const tasks: PlanTask[] = p.tasks.map((t, i) => ({
    id: t.id ?? `t${i + 1}`,
    title: t.title ?? '(untitled)',
    description: t.description ?? '',
    files: Array.isArray(t.files) ? t.files.map(String) : [],
    acceptance: t.acceptance ?? ''
  }));
  return { summary: String(p.summary), test_command: String(p.test_command), tasks };
}

export function planToMarkdown(plan: Plan): string {
  const lines: string[] = [];
  lines.push(`### Plan: ${plan.summary}`);
  lines.push('');
  for (const t of plan.tasks) {
    lines.push(`* [ ] **${t.id}** — ${t.title}`);
  }
  lines.push('');
  lines.push(`Test: \`${plan.test_command}\``);
  return lines.join('\n');
}

export function planToMarkdownDetailed(plan: Plan): string {
  const lines: string[] = [planToMarkdown(plan), '', '<details><summary>Details</summary>', ''];
  for (const t of plan.tasks) {
    lines.push(`**${t.id}** — ${t.title}`);
    lines.push(`- Files: ${t.files.map((f) => `\`${f}\``).join(', ') || '(open scope)'}`);
    if (t.description) lines.push(`- Change: ${t.description}`);
    if (t.acceptance) lines.push(`- Verify: ${t.acceptance}`);
    lines.push('');
  }
  lines.push('</details>');
  return lines.join('\n');
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 3 — EXECUTE: agent loop with write/edit tools for ONE task
// ───────────────────────────────────────────────────────────────────────────────
async function phaseExecute(
  cfg: LlmConfig,
  task: PlanTask,
  priorFailureHint: string | undefined,
  ctx: ToolContext,
  shouldStop: () => boolean,
  agentBody?: string,
  contextFiles?: string,
  onLlmCall?: OrchestratorOptions['onLlmCall'],
  stream?: PhaseStream
): Promise<string> {
  const base = [
    'You are a senior engineer executing ONE task. You have tools: read_file, write_file, edit_file, grep, glob.',
    '',
    'Tool-call format (MANDATORY):',
    '<tool_call>',
    '{"name": "tool_name", "arguments": {...}}',
    '</tool_call>',
    '',
    'Emit ONE tool_call per message. Read before you edit. After the task is done, emit a message with NO tool_call summarizing what changed.',
    'Do NOT run tests — the orchestrator will. Do NOT touch files outside the task scope.'
  ].join('\n');
  const messages: ChatMessage[] = [
    { role: 'system', content: buildSystemPrompt(base, agentBody, contextFiles) },
    {
      role: 'user',
      content: [
        `Task ${task.id}: ${task.title}`,
        `Files in scope: ${task.files.join(', ') || '(open — use glob/grep to find them)'}`,
        `What to do: ${task.description}`,
        `Acceptance: ${task.acceptance}`,
        priorFailureHint ? `\nPrevious attempt failed with:\n${priorFailureHint}\nFix the issue this time.` : ''
      ].filter(Boolean).join('\n')
    }
  ];

  const execSchemas = [
    ALL_TOOLS.read_file.schema,
    ALL_TOOLS.write_file.schema,
    ALL_TOOLS.edit_file.schema,
    ALL_TOOLS.grep.schema,
    ALL_TOOLS.glob.schema
  ];
  onLlmCall?.(`EXECUTE:${task.id}`, messages, execSchemas);

  let lastText = '';
  await runAgent(messages, {
    cfg,
    allowedTools: ['read_file', 'write_file', 'edit_file', 'grep', 'glob'],
    maxIterations: 10,
    autoApprove: new Set(['read_file', 'write_file', 'edit_file', 'grep', 'glob']),
    ctx,
    onMessage: (m) => { if (m.role === 'assistant' && m.content) lastText = m.content; },
    onToolCall: () => {},
    onToolResult: () => {},
    shouldStop,
    onStreamStart: stream?.onStart,
    onStreamChunk: stream?.onChunk,
    onStreamEnd: (msg) => stream?.onEnd?.(msg.content || '')
  });
  onLlmCall?.(`EXECUTE:${task.id}:done`, messages, execSchemas);
  return lastText;
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 4 — TEST: run the test command via bash tool
// ───────────────────────────────────────────────────────────────────────────────
async function phaseTest(
  cfg: LlmConfig,
  testCmd: string,
  ctx: ToolContext,
  shouldStop: () => boolean
): Promise<{ passed: boolean; output: string }> {
  // Bypass LLM — bash tool handler is called directly. Test phase is always auto-approved.
  const bashHandler = ALL_TOOLS.bash;
  const output = await bashHandler.run(
    { command: testCmd, timeout_ms: 300_000 },
    { ...ctx, approve: async () => true } // test phase auto-approved
  );
  const passed = /exit code:\s*0(?:\s|$)/.test(output);
  return { passed, output };
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 5 — FIX: summarize test failure into a hint for the next execute attempt
// ───────────────────────────────────────────────────────────────────────────────
export interface FixOutcome {
  hint: string;
  newTestCommand?: string; // if FIX decides the original test_command was wrong for this project
}

async function phaseFix(cfg: LlmConfig, taskTitle: string, currentTestCommand: string, testOutput: string, agentBody?: string, contextFiles?: string, onLlmCall?: OrchestratorOptions['onLlmCall'], stream?: PhaseStream): Promise<FixOutcome> {
  const base = [
    'Analyze a failing test output. Output format (strictly):',
    'Line 1 (optional): `TEST_COMMAND: <better-command>` — ONLY if the current test command is clearly wrong for this project type (e.g. `npm test` on a Python project; `pytest` on a Java project; `jest` with no jest installed).',
    'Remaining (max 150 words): concise hint listing (1) what failed, (2) probable file:line, (3) one concrete fix direction. No code.',
    '',
    'If the test command is fine and only the code needs changing, OMIT Line 1 entirely and write the hint directly.'
  ].join('\n');
  const msgs: ChatMessage[] = [
    { role: 'system', content: buildSystemPrompt(base, agentBody, contextFiles) },
    { role: 'user', content: `Task: ${taskTitle}\nCurrent test command: ${currentTestCommand}\n\nTest output:\n${testOutput.slice(-4000)}` }
  ];
  onLlmCall?.('FIX', msgs, []);
  stream?.onStart?.();
  const res = await chat(cfg, msgs, [], stream?.onChunk ? { onChunk: stream.onChunk, shouldAbort: stream.shouldAbort } : undefined);
  stream?.onEnd?.(res.content || '');
  const raw = res.content || '(fix phase returned no hint)';
  const cmdMatch = /^\s*TEST_COMMAND:\s*(.+?)\s*$/m.exec(raw);
  if (cmdMatch) {
    const newCmd = cmdMatch[1].trim();
    const hint = raw.replace(cmdMatch[0], '').trim();
    return { hint: hint || '(no additional hint)', newTestCommand: newCmd };
  }
  return { hint: raw };
}

// ───────────────────────────────────────────────────────────────────────────────
// Phase 6 — REPORT: final markdown summary
// ───────────────────────────────────────────────────────────────────────────────
function buildReport(plan: Plan, outcomes: TaskOutcome[], v: RunVerdict): string {
  const executed = outcomes.filter((o) => o.status === 'executed').length;
  const errored = outcomes.filter((o) => o.status === 'errored').length;
  const skipped = outcomes.filter((o) => o.status === 'skipped').length;
  const verdictLabel = v.testPassed
    ? 'PASSED'
    : errored > 0 || skipped > 0
      ? 'FAILED'
      : 'TESTS FAILED';

  const lines: string[] = [];
  lines.push(`### Report: ${plan.summary}`);
  lines.push('');
  for (const o of outcomes) {
    const mark = o.status === 'executed' ? 'x' : o.status === 'skipped' ? '-' : ' ';
    const suffix = o.status === 'executed'
      ? ''
      : o.status === 'skipped'
        ? ' (skipped)'
        : ` (errored — ${o.notes.replace(/\n/g, ' ').slice(0, 80)})`;
    lines.push(`* [${mark}] **${o.id}** — ${o.title}${suffix}`);
  }
  lines.push('');
  lines.push(`${verdictLabel} · executed ${executed} / errored ${errored} / skipped ${skipped} · fix retries ${v.fixAttempts} · test: \`${plan.test_command}\``);
  if (!v.testPassed) {
    lines.push('');
    lines.push('<details><summary>Last test output</summary>');
    lines.push('');
    lines.push('```');
    lines.push(v.finalTestOutput.slice(-2000));
    lines.push('```');
    lines.push('</details>');
  }
  return lines.join('\n');
}

// ───────────────────────────────────────────────────────────────────────────────
// Main orchestrator
// ───────────────────────────────────────────────────────────────────────────────
export async function orchestrate(
  opts: OrchestratorOptions,
  cb: OrchestratorCallbacks
): Promise<void> {
  const maxFix = opts.maxFixAttempts || FIX_CAP_DEFAULT;

  const pa = opts.phaseAgents ?? {};
  const ctxFiles = opts.contextFiles;

  // 1. READ
  cb.onPhase('READ', 'enriching goal');
  if (cb.shouldStop()) return;
  const enriched = await phaseRead(opts.cfg, opts.goal, ctxFiles, opts.onLlmCall, mkPhaseStream(opts, 'READ'));

  // 2. PLAN
  cb.onPhase('PLAN', 'generating JSON plan');
  if (cb.shouldStop()) return;
  const plan = await phasePlan(opts.cfg, enriched, pa.plan, ctxFiles, opts.onLlmCall, mkPhaseStream(opts, 'PLAN'));
  cb.onPhase('PLAN', `${plan.tasks.length} tasks — awaiting approval`);

  const approved = await cb.onPlan(plan);
  if (!approved) {
    cb.onPhase('CANCELLED', 'user rejected plan');
    cb.onReport(`## Cancelled\nUser rejected the plan.\n\n${planToMarkdown(plan)}`);
    return;
  }

  // 3. EXECUTE — run all tasks sequentially, no test between tasks
  const outcomes: TaskOutcome[] = [];
  for (const task of plan.tasks) {
    if (cb.shouldStop()) {
      outcomes.push({ id: task.id, title: task.title, status: 'skipped', notes: 'stopped by user' });
      continue;
    }
    cb.onPhase('EXECUTE', task.id);
    try {
      const note = await phaseExecute(opts.cfg, task, undefined, opts.ctx, cb.shouldStop, pa.execute, ctxFiles, opts.onLlmCall, mkPhaseStream(opts, `EXECUTE:${task.id}`));
      outcomes.push({ id: task.id, title: task.title, status: 'executed', notes: note.slice(0, 120) });
    } catch (e) {
      outcomes.push({
        id: task.id,
        title: task.title,
        status: 'errored',
        notes: e instanceof Error ? e.message : String(e)
      });
    }
  }

  // 4. TEST — single verification run after all tasks finish
  cb.onPhase('TEST', `running ${plan.test_command}`);
  let testRes = await phaseTest(opts.cfg, plan.test_command, opts.ctx, cb.shouldStop);
  let fixAttempts = 0;

  // 5. FIX loop — retry on failed test only. Each retry: fix hint + synthetic fix task + re-test.
  while (!testRes.passed && fixAttempts < maxFix && !cb.shouldStop()) {
    fixAttempts++;
    cb.onPhase('FIX', `analyzing failure (retry ${fixAttempts}/${maxFix})`);
    const fixOut = await phaseFix(opts.cfg, plan.summary, plan.test_command, testRes.output, pa.fix, ctxFiles, opts.onLlmCall, mkPhaseStream(opts, `FIX:${fixAttempts}`));
    const hint = fixOut.hint;
    if (fixOut.newTestCommand && fixOut.newTestCommand !== plan.test_command) {
      cb.onPhase('FIX', `test_command updated: "${plan.test_command}" → "${fixOut.newTestCommand}"`);
      plan.test_command = fixOut.newTestCommand;
    }
    if (cb.shouldStop()) break;

    const allFiles = [...new Set(plan.tasks.flatMap((t) => t.files))];
    const fixTask: PlanTask = {
      id: `fix-${fixAttempts}`,
      title: `Fix test failure (retry ${fixAttempts})`,
      description: hint,
      files: allFiles,
      acceptance: `\`${plan.test_command}\` exits 0`
    };
    cb.onPhase('EXECUTE', fixTask.id);
    try {
      await phaseExecute(opts.cfg, fixTask, hint, opts.ctx, cb.shouldStop, pa.execute, ctxFiles, opts.onLlmCall, mkPhaseStream(opts, `EXECUTE:${fixTask.id}`));
    } catch (e) {
      // continue — next test run will reveal state
    }
    if (cb.shouldStop()) break;

    cb.onPhase('TEST', `re-running ${plan.test_command}`);
    testRes = await phaseTest(opts.cfg, plan.test_command, opts.ctx, cb.shouldStop);
  }

  // 6. REPORT
  cb.onPhase('REPORT', 'building summary');
  const verdict: RunVerdict = {
    testPassed: testRes.passed,
    fixAttempts,
    finalTestOutput: testRes.output
  };
  cb.onReport(buildReport(plan, outcomes, verdict));
}
